### ISSUE TITLE
earth acceleration direction convention_enu

### ISSUE THREAD

**Issue by songtao-git** [xioTechnologies/Fusion#107]
Hello, I would like to confirm if my understanding of the direction of earth acceleration is correct. If I specify CONVENTION_ENU, then x corresponds to the north, y corresponds to the east, and z corresponds to downwards?

I am setting different heading values in ahrs. Will this affect x， y and z of earth acceleration?

The complete scenario for which I am consulting this question is for a car-mounted inertial navigation system. I can obtain position, heading and velocity data through GNSS:
1. Set the initial position and velocity through GNSS data, including heading if necessary.
2. Calculate the vehicle’s acceleration through ahrs’ earth acceleration, then speed, and then new position. This can achieve the scenario of car-mounted inertial navigation.
3. If there is a need for calibration during parking or uniform straight-line motion, GNSS data can be used to calibrate the inertial navigation system.

I am eagerly waiting for your reply

**Comment by xioTechnologies** [comment]
ENU means East = X, North = Y, and Up = Z.  The three letters correspond to XYZ, in order.  The heading will determine how accelerometer measurements map onto the Earth's XY plane.

**Comment by songtao-git** [comment]
I read that in the Earth coordinate frame, the z-axis points to the North Pole and the x and y are in the equatorial plane. However, ENU that you mentioned earlier seems more like a navigation coordinate system, so I’m a bit confused.

**Comment by xioTechnologies** [comment]
[Axes Conventions](https://en.wikipedia.org/wiki/Axes_conventions) describe how the XYZ directions are assigned to the Earth coordinate frame.  Fusion supports three different axes conventions: North-West-Up (NWU), East-North-Up (ENU), and North-East-Down (NED).  If you are confused then I suggest you either ask a specific question, or search online to fill the gaps in your knowledge.

**Comment by songtao-git** [comment]
thanks!
