### ISSUE TITLE
Python how to read quaternion

### ISSUE THREAD

**Issue by Jason-Dellai** [xioTechnologies/Fusion#11]
Hi, thanks for your work.
I'm curently using imufusion in order to determine the orientation of differents IMU, but i don't find how to read the quaternion before the convertion to euler  angle. How can i directly read the quaternion output ?

**Comment by DocSunset** [comment]
On Python/Python-C-API/Quaternion.h around line 82 you can see get/set definitions for the quaternion python object. So I believe if you have an ahrs object `ahrs`, you could read the quaternion as `ahrs.quaternion.array` or `ahrs.quaternion.w; ahrs.quaternion.x; # etc`

It would be nice to have more approachable documentation besides the source code, but the Python-C-API is reasonably readable, so I can understand why the maintainer(s) might choose to prioritize other things.

**Comment by Jason-Dellai** [comment]
Thanks for your answer it works
