### ISSUE TITLE
Is manual calibration needed?

### ISSUE THREAD

**Issue by andrasj** [xioTechnologies/Fusion#11]
I see my roll/pitch angles don't go up to 90 degrees. As "calibrationdata", I took the values from the datasheet.
Could the reason be I need to measure min/max for calibration of accelerometers?

**Comment by xioTechnologies** [comment]
Sensor datasheets indicate the nominal values of characteristics such as sensitivity and offset.  Accurate sensor measurements require that you determine use the actual values of these characteristics.
