### ISSUE TITLE
Magnetic disturbance effect on yaw

### ISSUE THREAD

**Issue by Lelelo1** [xioTechnologies/Fusion#13]
I have read some articles that describe a perk of the madgwick algorithm in terms of magnetic disturbance. It is said to being able to have it affect only one axis, yaw.

> By reducing the constraint of the magnetic field vector rotation, it can limit the effect of the magnetic disturbances to only affect the yaw component of the orientation

http://www.ijcee.org/vol10/974-T4004.pdf

> Compensating for magnetic distortions in this way ensures that magnetic disturbances are limited to only affect the estimated heading component of orientation

https://www.x-io.co.uk/res/doc/madgwick_internal_report.pdf

---

I think this should mean that I can put a fixed value of z in the orientation (like 0) temporarily, disturb the magnetometer with a metallic fork - and not see any effect in the orientation.
This is not the case. How come I am not seeing this behaviour (neither in the C# version of the algorithm - nor in this C version) - have I misunderstood the descriptions given in the articles?

**Comment by xioTechnologies** [comment]
I expect that the metal fork is affecting the magnetic field in the X and Y directions.  The magnitude of the magnetic field in the Earth's Z axis has no effect on the measured direction of magnetic north.

**Comment by Lelelo1** [comment]
This is on a mobile device - with an app containing augmented reality UI elements. I don't expect them to move while the device is still and I bring the metal fork and having yaw set to fixed value of 0. It does not make sense if those statements are valid?
I am just inspecting the orientation here.

**Comment by Lelelo1** [comment]
I read more about ahrs here: https://www.vectornav.com/resources/attitude-heading-reference-system

Now I understand it as the role of the magnetometer in any ahrs is to provide the yaw information. I got a faulty impression that the disturbance in yaw was an outcome of how madgwick was constructed

**Comment by Lelelo1** [comment]
It should mean I should be able to put `0` in z - in all sensor updates without seeing any direction changes in the AR app I am developing. For them to appear correctly, it seems I am needing the full magnetometer vector at all times
