### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by avsaase** [xioTechnologies/Fusion#134]
Hi, thanks for your work. I would like to use this algorithm in a Rust project. I considered porting the code but then I found [this comment](https://github.com/jmagnuson/ahrs-rs/issues/21#issuecomment-1369023131) where you stated you'd prefer wrapping the C library. I don't know C all that well but I would like to give this a try. Would a Rust library be in scope for this repository?

**Comment by mark2b** [comment]
I've ported this library to Rust and just published it hour ago
Please look at
https://github.com/mark2b/imu-fusion-rs
It is not binding, but Rust native implementation

**Comment by xioTechnologies** [comment]
It sounds like @mark2b has what you need.

It is within the scope of this repository to provide a Rust library that wraps the C library, but we are unlikely to make progress on this until required by a project or client.

**Comment by avsaase** [comment]
HI @xioTechnologies, are you interested in a PR that adds Rust bindings? I gave it a try and it turned out to be quite easy.

**Comment by xioTechnologies** [comment]
I would be interested in seeing the code but we would not merge external PRs.

**Comment by avsaase** [comment]
Why is that?

You can find the code in my fork here: https://github.com/avsaase/Fusion/tree/rust-bindings

**Comment by xioTechnologies** [comment]
To maintain quality.  Thank you for sharing.

**Comment by avsaase** [comment]
Note that the bindings are currently not tested and could break in potentially subtle ways when the the C library changes.

I'll set up a separate repo and continue the development there.
