### ISSUE TITLE
Sensors axis orientation and heading/yaw

### ISSUE THREAD

**Issue by Nate409** [xioTechnologies/Fusion#14]
Hello.
I've got some questions about Fusion.

1. Sensors axis orientation for "_FusionAhrsUpdate_" function and "_FusionCompassCalculateHeading_" should be NWU and all sensors axes should be aligned between each other, right?
For example, there are two sensor chips on the PCB: magnetometer chip and gyro/accel chip. 
And sensors axes pointed in different directions: 
- magnetometer -> x to North, y to West, and z Up;  
- gyro/accel  -> x to East, y to North and z Up;

So  sensors data for the Fusion should be aligned to NWU:
- For Gyro
	    _FusionGyro.x = sensorGyro.y
	    FusionGyro.y = -sensorGyro.x
	    FusionGyro.z = sensorGyro.z_
- Accel same as a gyro.
- For magnetometer
	    _FusionMag.x = sensorMag.x
	    FusionMag.y = sensorMag.y
	    FusionMag.z = sensorMag.z_

Is it right?

2. What difference between yaw calculated by the "_FusionAhrsUpdate_" function and the compass heading calculated by the "_FusionCompassCalculateHeading_" function?

3. In "**ExampleCompass.c**" it is said:
_"// The contents of this do while loop should be called for each time new sensor measurements are available"_
What was meant by "new sensor measurements" - magnetometer or accel measurement?

**Comment by xioTechnologies** [comment]
1. If you mount a chip with it's Y axis pointing in the direction of what you intend to be the X axis then you must provide the Y axis measurement as that of the X axis.
2. The heading calculated by `FusionAhrsUpdate` uses the gyroscope, the heading calculated by `FusionCompassCalculateHeading` does not.
3. "New sensor measurements" refers to whatever sensor measurements are required.  If the update requires accelerometer and magnetometer measurements then these should be provided.

**Comment by Nate409** [comment]
Thank you for the answers.)

Could you please advise what output data rate (ODR) for the accelerometer, gyroscope, and magnetometer would be suitable for more accurate calculations?
Maybe there is some rule of thumb for this.

**Comment by xioTechnologies** [comment]
Higher update rates will be provide greater accuracy.  Most applications will require a sample rate of around 200 Hz.

**Comment by Nate409** [comment]
Thank you.)
