### ISSUE TITLE
Linear/earth acceleration very slow to catch up with movement

### ISSUE THREAD

**Issue by sylque** [xioTechnologies/Fusion#141]
Hi Xio team,
When I rotate my IMU by 90° and put it down, the Euler angles are updated almost immediately, but the linear and earth acceleration are very slow to converge back to zero (several seconds). Is it to be expected?
Thanks,
Syl

**Comment by sylque** [comment]
Sorry, my mistake, I was watching lpf-filtered values!

**Comment by Kievkao** [comment]
@sylque I have same problem, could you please explain with a bit more details what do you mean? You have some additional low-pass filter applied to Fusion output?

**Comment by sylque** [comment]
Yes, I had a low-pass filter applied to the output. That is what I was monitoring, instead of the direct output.
