### ISSUE TITLE
TEST data

### ISSUE THREAD

**Issue by RomanSmalia** [xioTechnologies/Fusion#143]
Hi. 
Does the project have test data? I tried the library on my NGIMU v1.6  and got very incomprehensible data.

**Comment by xioTechnologies** [comment]
The [Python examples](https://github.com/xioTechnologies/Fusion/tree/main/Python) in this repository include example data.  There is also the [Gait Tracking](https://github.com/xioTechnologies/Gait-Tracking) repository that uses Fusion, and [IMU Simulator](https://github.com/xioTechnologies/IMU-Simulator) for synthetic data.
