### ISSUE TITLE
Python "No code object available for imufusion" with Setup.py or pip install

### ISSUE THREAD

**Issue by crashmatt** [xioTechnologies/Fusion#147]
python will not properly import imufusion for me. It fails on:

python -m imufusion results in:
"No code object available for imufusion"

Installed to venv and --user and got the same result

On Ubuntu 22.04.04

**Comment by crashmatt** [comment]
It fails on:
ahrs = imufusion.Ahrs()

imufusion.Ahrs is not recognized

**Comment by crashmatt** [comment]
Nevermind.  Fixed it.  Failed to explicit use ==1.2.2

**Comment by xioTechnologies** [comment]
There was an issue with the [v1.2.3 release actions](https://github.com/xioTechnologies/Fusion/actions/runs/7503698584).  This will be fixed on Wednesday.  The only changes between v1.2.2 and v1.2.3 are Python package platform support.

**Comment by crashmatt** [comment]
Thanks for the support.

/Matt
