### ISSUE TITLE
[Question] What is the expected orientation by the sensor fusion algorithm? 

### ISSUE THREAD

**Issue by cparata** [xioTechnologies/Fusion#15]
Hello,
I'm trying this great sensor fusion algorithm. I would like to know what is the expected orientation of the sensor data as input of the sensor fusion algorithm. Is it E-N-U or N-E-D? What is the output orientation?
Thanks in advance for the clarification.
Best Regards,
Carlo

**Comment by xioTechnologies** [comment]
The [README](https://github.com/xioTechnologies/Fusion#readme) states, _"The quaternion describes the orientation of the sensor relative to the Earth using the North-West-Up (NWU) convention._"

**Comment by cparata** [comment]
Ok, thanks. So, I guess that also the input of the sensors are expected with the same convention, correct?

**Comment by xioTechnologies** [comment]
ENU, NED, and NWU are conventions that describe the Earth axis directions.  For example, ENU means X = East, Y = North, and Z = Up.  Such conventions have no meaning applied to the sensors because the sensors move relative to the Earth.

**Comment by cparata** [comment]
Ok, thanks.
I close this issue.
