### ISSUE TITLE
Quaternion x and z values are the same

### ISSUE THREAD

**Issue by simon88** [xioTechnologies/Fusion#15]
I'am working with you source code and one [LSM6DSO32](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjq58uH9JbyAhVrhv0HHRV-CXgQFnoECAYQAw&url=https%3A%2F%2Fwww.st.com%2Fresource%2Fen%2Fdatasheet%2Flsm6dso32.pdf&usg=AOvVaw1fMU6I3TJJnY-tmKI0Afgf)
Everything works but as you can see at the page 22, if I set my captor with x point down or orient up like if x is z, I have an issue when I get my quaternion with `FusionAhrsGetQuaternion`x and Z values are the same, if I turn my captor around x axis my x and z values evolved together. 
If I print my raw value coming from my captor, my values are good, if I rotate around x only x raw value changed (gyro and accelerometer).
I don't have the problem if I do the same with y in place of z....

Example of data of initialisation
`q.w : 0.71	q.x : -0.22	q.y : 0.64	q.z : -0.19	accel x : 9.90	accel y : 0.14	accel z : 0.78	gyro x : 0.00	gyro y : 0.00	gyro z : -0.02`

As you can see q.x and q.y are almost the same, so now if I rotate my captor around x axis for about 45°
`q.w : 0.52	q.x : -0.51	q.y : 0.45	q.z -0.51   accel x : 9.94	accel y : -0.26	accel z : 0.72	gyro x : 1.08	gyro y : -0.03	gyro z : -0.02`

As you can see q.x and q.z evolved together but in my raw data I've only gyro x changed.

I've also try to used `FusionAhrsSetYaw` but without succes my yaw value is never set to zero this i sstrange, but if I set my y for example orient up or down like if y is z and I used `FusionAhrsSetYaw` yaw value is set to zero.

**Comment by xioTechnologies** [comment]
I do not see the issue.  I suggest you convert the quaternion to Euler angles.  Perhaps this will be the behaviour you are expecting.

**Comment by simon88** [comment]
No I don't want to work with Euler angles because I'am working at the limit and in the limit of the Gimbal lock with my captor.
I don't understand why if I call `FusionAhrsSetYaw(fusionAhrs, 0.0f);` every time in `FusionAhrsUpdateWithoutMagnetometer` function my z value of my quaternion isn't set to zero

**Comment by xioTechnologies** [comment]
You have a fundamental misunderstanding about what quaternions are and how they work.
