### ISSUE TITLE
Measurement convention for sensors other than x-imu

### ISSUE THREAD

**Issue by maker-ATOM** [xioTechnologies/Fusion#150]
For to use Fusion algorithm for motion tracking of objects like demostrated in [Gait-tracking](https://github.com/xioTechnologies/Gait-Tracking) with different sensors available like BNO055, it is necessary for the sensor to include gravitational measurements within Accelerometer.

For example if the sensor is lying flat on a table surface with z-axis pointing upwards should the sensor measure (0.0, 0.0, 0.0) g or (0.0, 0.0, 1.0) g.

**Comment by xioTechnologies** [comment]
I do not understand your comment.  If you are asking a question then please phrase your comment as a question.

**Comment by maker-ATOM** [comment]
If I have to use Fusion Algorithm with sensors other than x-imu what conventions do I need to follow?

**Comment by xioTechnologies** [comment]
Fusion is a general purpose library.  There is nothing about Fusion that ties it to the x-IMU or any other product.
