### ISSUE TITLE
Link to dissertation is broken

### ISSUE THREAD

**Issue by ib00** [xioTechnologies/Fusion#157]
It appears that the link to the PhD dissertation is broken.

Any alternative source for it?

**Comment by xioTechnologies** [comment]
The error appears to be temporary.  The external link returns the following message.

> We're continuing to experience a major technology outage as a result of a [cyber-attack](https://www.bl.uk/cyber-incident/). Our buildings are open as usual, however, the outage is still affecting our website, online systems and services, as well as some onsite services.
> This is a temporary website, with limited content, which outlines the services that are currently available, as well as what's on at the Library."

Please [contact us](https://x-io.co.uk/contact/) to resolve this by email.
