### ISSUE TITLE
Very noisy Roll Pitch  Yaw data

### ISSUE THREAD

**Issue by YunHB** [xioTechnologies/Fusion#159]
Hello. Thank you for those nice libraries.

I'm trying to use those libraries for MARG sensor fusion, and when I logged those data I got data with huge noise.
I am thinking of calibration of sensors and introduction of low-pass filters for sensor data as a solution to the noise.

May I get some hints with your opinion?

I used the c headers and sources.

those pictures are compared shots with commercial IMU module.
![스크린샷 2024-04-19 142308](https://github.com/xioTechnologies/Fusion/assets/161276496/9ffe6a01-e480-403a-944b-21dc13d4ac18)
![스크린샷 2024-04-19 142344](https://github.com/xioTechnologies/Fusion/assets/161276496/a7349692-09e5-4ffa-8a58-91804a9f1b12)
![스크린샷 2024-04-19 142426](https://github.com/xioTechnologies/Fusion/assets/161276496/779effc1-b790-466a-b502-9c6563f395db)

**Comment by xioTechnologies** [comment]
It looks like your Euler angles are garbage, not noisy.  I suggest you format your sensor data into a [CSV file](https://github.com/xioTechnologies/Fusion/blob/main/Python/sensor_data.csv) to be processed by [simple_example.py](https://github.com/xioTechnologies/Fusion/blob/main/Python/simple_example.py).  This will plot gyroscope, accelerometer, and Euler angles side-by-side as shown below.  This plot may offer some insight as to what is going on.

![image](https://github.com/xioTechnologies/Fusion/assets/1748389/467a22a7-a50e-40b4-9125-36813a12339f)

**Comment by YunHB** [comment]
It looks like garbage, but with same imu, same sensors, other algorithm got very accurate euler angle data.
And the difference I found between those two algorithm is existence of LPF on sensor data.
I will try your suggestion, but I think it won't make this better.

**Comment by xioTechnologies** [comment]
My suggestion will not make it better because I did not suggest a solution.  I suggested that you provide plots that would hopefully allow us to see what the problem is.

**Comment by YunHB** [comment]
OH that was my misunderstanding, sorry. I applied LPF and HPF on sensor data, and I got a better plot. Maybe the sensors have too much noise or I treated them in unstable condition. 
![100hz_pitch](https://github.com/xioTechnologies/Fusion/assets/161276496/a5fc4425-afdc-4608-a33e-d973501eec81)
![100hz_roll](https://github.com/xioTechnologies/Fusion/assets/161276496/7f93d363-c723-43a0-bd59-85b8f92e53e1)
![100hz_yaw](https://github.com/xioTechnologies/Fusion/assets/161276496/e36b3c02-2e66-40c0-8e21-e15d8c4758f3)

**Comment by xioTechnologies** [comment]
If you are not going to engage with this support then please close the issue.
