### ISSUE TITLE
What format is input gyroscope and accel?

### ISSUE THREAD

**Issue by David-OConnor** [xioTechnologies/Fusion#16]
```c
 * @param gyroscope Gyroscope measurement in degrees per second.
void FusionAhrsUpdate(FusionAhrs *const ahrs, const FusionVector gyroscope, const FusionVector accelerometer, const // ...
```

I have three guesses:
- Pitch, roll, yaw
- Roll, pitch, yaw
- Normalized 3d vector x, y, z, ie requires processing of raw gyro measurements into a vector. (Most likely?)

Re accel: I'm assuming it's x, y, z. Is that correct?

Thank you!

**Comment by xioTechnologies** [comment]
The type of the argument `gyroscope` is `FusionVector`.  This is a structure with three members: `x`, `y`, and `z`.  These are the x, y, and z axis measurements provided by the gyroscope.

Pitch, roll, and yaw are Euler **angles**.  These terms are not applicable to gyroscope measurements of **angular velocity**.  The word "normalized" has a [specific meaning](https://en.wikipedia.org/wiki/Unit_vector) when referring to vectors.  The gyroscope vector should not be normalised.

**Comment by David-OConnor** [comment]
Thank you for the detailed explanation!

The IMU gyroscopes I've dealt with measure angular velocity in 3 axes, which can be described a pitch, roll, and yaw. How would you use these in this library's update function API?

```c
typedef union {
    float array[3];

    struct {
        float x;
        float y;
        float z;
    } axis;
} FusionVector;
```

My best guess is the mapping is `x`: pitch, `y`: roll, `z`: yaw, based on the axes of rotation.

Both the gyro and accel readings are of type `FusionVector`. This makes sense for the accelerator, since it really is an acceleration vector in 3 axes. It's a bit... muddier for the gyro.

**Comment by xioTechnologies** [comment]
Gyroscope axes are usually described as: x, y, and z.  It sounds like the gyroscope you are using has instead assigned the labels: pitch, roll, and yaw.  The correspondence of these labels is ambiguous.  Are you able to share a link to the documentation?

**Comment by David-OConnor** [comment]
Looking at the datasheet, it's described as you say - around the X, Y, and Z axes. The pitch/yaw/roll terminology isn't part of the IMU, but a convention I've been using, where x, y, and z are linear directions, and pitch, roll, and yaw are angular directions. With this in mind, your explanation solves this entirely. Thank you very much!

![image](https://user-images.githubusercontent.com/4590796/168484613-2c6fe0a2-f3c4-454b-81cd-89ae9d5ed88c.png)

So, the mapping I'm now using, from an internal struct works out to be:
```rust
let gyro_data_for_ahrs = Vec3 {
    x: imu_data.v_pitch,
    y: imu_data.v_roll,
    z: imu_data.v_yaw,
};
let accel_data_for_ahrs = Vec3 {
    x: imu_data.a_x,
    y: imu_data.a_y,
    z: imu_data.a_z,
};
```

**Comment by David-OConnor** [comment]
Fixed by https://github.com/xioTechnologies/Fusion/issues/9
