### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by simon88** [xioTechnologies/Fusion#16]
I'am working with your code everything works but I have a question about `FusionAhrsSetYaw` I'd like to do the same but for pitch or roll for example, so if I want to set `x` to a specific angle should I only put `-1.0f * sinf(halfInverseYawMinusOffset),`in `element.x`? Or should I also change this line `atan2f(Q.x * Q.y + Q.w * Q.z, Q.w * Q.w - 0.5f + Q.x * Q.x);`?

Second question, if I understand well your code `FusionAhrsInitialise(&fusionAhrs, 0.5f);`the value `0.5` is the gain, more low is the gain more gyroscope value are true is it right? So just for my information how can calculate this value, I don't know if it's work like that but imagine I want to "trust" gyro value at 80% and accelerometer value at 20% how can I determine the gain ?

Thanks for you work!

**Comment by xioTechnologies** [comment]
The mats for setting the pitch/roll are too complex to go into here.  A low gain trusts the gyroscope more, a high gain trusts the gyroscope less.  A value of 0.5 is appropriate for most applications.  The units of the gain cannot be easily described.  It is not possible to express this quantity as a ratio or percentage.

**Comment by simon88** [comment]
Thanks for your answer. Do you have an example or a document to explain maths for setting pitch/roll ? I'am really interested about this subject.

**Comment by xioTechnologies** [comment]
I'm afraid not.
