### ISSUE TITLE
Recommended sampling rate?

### ISSUE THREAD

**Issue by ib00** [xioTechnologies/Fusion#160]
What are the minimum and recommended sampling rates for the IMU sensor for the fusion algorithm to stable
and usable?

**Comment by xioTechnologies** [comment]
An appropriate sample rate will depend on the application.  If you are unsure then I suggest you start with 100 Hz.  Less than 50 Hz will often cause problems, and more than 400 Hz will offer diminishing returns.  The algorithm only utilises first-order feedback processes and so cannot become [unstable](https://en.wikipedia.org/wiki/Instability#Instability_in_control_systems).

**Comment by ib00** [comment]
Thanks for the answer.
