### ISSUE TITLE
5 seconds delay in real-time operation (python)

### ISSUE THREAD

**Issue by paulasimoUPC** [xioTechnologies/Fusion#166]
Hi, 

Thank you for sharing your work with the community. I am reading the data from a sensor in real-time through serial connection and processing it in real-time. I have noticed a five seconds delay on the calculation of the orientation using python. I suspect the error comes from the time that the library needs to process the data. Is it possible to correct this?

Please let me know if you need more information to be able to answer my question. 

Thank you for your time.

**Comment by xioTechnologies** [comment]
No, your suggestion is not correct.  The algorithm processing time has not been profiled for Python but I expect it will be in the order of microseconds.

**Comment by paulasimoUPC** [comment]
Hi,

Thank you very much for your fast response. It seems it was a problem with the gyroscope units.
