### ISSUE TITLE
data advice request

### ISSUE THREAD

**Issue by SimoneCaiati** [xioTechnologies/Fusion#177]
hi, I am using the algorithm and some doubts have arisen. i noticed that the units used are in G for acceleration and deg/s for gyro. However, my sensor only collects in m/s^2 and rad/s. is it necessary for me to have to use these units or is there a way to use the ones I already have? if not, should I do the data conversion before applying the algorithm or after?
sorry for the stupid question, but i would like some confirmation.
thanks in advance.

**Comment by xioTechnologies** [comment]
You must use the correct units.  You can convert rad/s to deg/s using [`FusionRadiansToDegrees`](https://github.com/xioTechnologies/Fusion/blob/main/Fusion/FusionMath.h#L136); and m/s^2 to g by dividing by 9.81.  For example, 9.81 m/s^2 = 1 g.
