### ISSUE TITLE
Algorithm problems

### ISSUE THREAD

**Issue by viatto** [xioTechnologies/Fusion#18]
Hi, I tried to use this algorithm to obtain the acceleration in the global reference frame by multiplying accelerometer data for the rotation matrix obtained by the Madgwick filter. When I move the object in the direction of one axis, I notice that the acceleration rises in all the axis almost equally.  What can I do to solve the problem?

**Comment by xioTechnologies** [comment]
Acceleration in the global reference frame is provided by the function `FusionAhrsGetEarthAcceleration`.  I suggest you use this function instead of implementing the calculation yourself.

**Comment by viatto** [comment]
Thank you, I will try! I am using the python library, Do i have to use the same input and output of the Matlab library?

**Comment by xioTechnologies** [comment]
No. Fusion is only available for C/C++ and Python.
