### ISSUE TITLE
Thesis availability

### ISSUE THREAD

**Issue by mjs513** [xioTechnologies/Fusion#181]
The link in the readme to Dr. Madgwick's thesis appears to be broken.  

Just wanted to let you know.

**Comment by mvschaefer** [comment]
if you find a copy, please lmk where to find it as well!..

**Comment by mjs513** [comment]
@mvschaefer 
Found I had put in a dropbox folder: https://www.dropbox.com/s/vuoppg0a6b5ttpb/681552_1681558641136.zip?dl=1

**Comment by mvschaefer** [comment]
@mjs513 - thanks for the light reading material!..

**Comment by xioTechnologies** [comment]
The link has been fixed.
