### ISSUE TITLE
Question: How to update AHRS when the Gyro and Accel sensors have different output data rates?

### ISSUE THREAD

**Issue by Mitchlol** [xioTechnologies/Fusion#19]
Hey, just a question, it might help others as well.

Lots of IMU units have varying output data rates for Gyro and Accel, I think I would get the best results by maximizing both of them, however I'm not sure how to call `FusionAhrsUpdate()` when my gyro data is updated, but my accel data is stale. The doc says "This function should be called for each new gyroscope measurement." does this mean I can call it as often as the Gyro (faster) updates, with stale Accel (slower) data, and the time since the last gyro update?

**Comment by xioTechnologies** [comment]
The update function should be called for each new gyroscope measurement.  If new measurements are not available for other sensors then the most recent measurements should be use.

This use of stale measurements is unlikely negatively impact performance.  Consider some example numbers, an accelerometer sample rate of 100 Hz for an IMU rotating continuously at 360 degrees/s.  The average lag in accelerometer observations relative to the gyroscope would be 5 ms, corresponding to a 1.8 degree error during the rotation.  The AHRS algorithm measurement error would be ~0.75 degrees after 1 second, ~1.4 degrees after 2 seconds, and ~1.8 degrees after 10+ seconds.

This is a small error for an extreme situation.  In most applications, an IMU would not rotate at speed for more than a fraction of a second.  To put this small error into context, consider that a typical gyroscope sensitivity tolerance of ±1% would result in 3.6 degree error after 1 second and a 36 degrees error after 10 seconds.

In practise, any errors that result of the use of stale measurements will likely be orders of magnitude less than the errors introduced elsewhere in the system.

**Comment by Mitchlol** [comment]
Thank you!
