### ISSUE TITLE
about HalfMagnetic vector calculation

### ISSUE THREAD

**Issue by Huangxianfeng001** [xioTechnologies/Fusion#194]
the calculation of in the equation of HalfMagnetic in your code seems different from the equation of Mahony algorithm.
In the function of HalfMagnetic, seems you directly transform the vector [0, 1, 0] from Global Coordinate  system to the Body Coordinate system. hope you can explain it.

**Comment by xioTechnologies** [comment]
`HalfMagnetic` returns the direction of the magnetic field scaled by 0.5.  This is the direction of the magnetic field according to the AHRS algorithm's current measurement of orientation.  The scaling by 0.5 is just to avoid redundant operations.
