### ISSUE TITLE
C99 "designated initializer style" not available on C++11

### ISSUE THREAD

**Issue by miccio-dk** [xioTechnologies/Fusion#2]
As per title. 
Can be replicated by including `Fusion.h` into any .cpp file. 
At that point, its compilation will trigger ~54 errors, all coming from the aforementioned header file.

I haven't investigated whether it would function with different dialects of the standard, so this might be a general C++ issue. 

Though most of these errors are related to the  `FusionVectorOperator` function, they can't be moved to a separate .c file as they are declared `inline`.
The only possible fix that comes to my mind is using a different initialization style for structs.

I can start working on a patch as soon as you confirm the above.

**Comment by xioTechnologies** [comment]
I can confirm errors when using the Arduino 1.6.12 C++ compiler.  All errors were fixed by modifying the way structure/union members are written to.  For example, to modify this...
```
    const FusionVector3 result = {
        .axis.x = vectorA.axis.x + vectorB.axis.x,
        .axis.y = vectorA.axis.y + vectorB.axis.y,
        .axis.z = vectorA.axis.z + vectorB.axis.z,
    };
    return result;
```
...to this:
```
    FusionVector3 result;
    result.axis.x = vectorA.axis.x + vectorB.axis.x;
    result.axis.y = vectorA.axis.y + vectorB.axis.y;
    result.axis.z = vectorA.axis.z + vectorB.axis.z;
    return result;
```
I would like to confirm that this change does not affect performance before committing.  Please can you confirm if this change fixes all of your compiler errors.

**Comment by xioTechnologies** [comment]
The correct term of the problematic syntax is "designated initializer":
https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html

This is supported by ANSI C99 but it appears not to be supported by the C++ compiler.

**Comment by xioTechnologies** [comment]
I assume form your pull request that you have confirmed the fix with your compiler.

**Comment by miccio-dk** [comment]
I ran my usual test file* and the behaviour hasn't been affected. Please check pull request #3 which should apply the suggested fix everywhere.

It's worth noting that I am currently only employing the AHRS functionalities of the Fusion suite, so more incompatibilities may arise. I'll deal with them as they appear.

You're right about the naming. The word _style_ is my title was referring to _initialization_, which I erroneously omitted. The perks of recklessly copy-pasting from Wikipedia.. :)


*May I suggest to include that in the repo? It's a bare source file that loads the raw sensor data you made available on the `NGIMU-MATLAB-Import-Logged-Data-Example` repo, and runs the AHRS filter on them.
