### ISSUE TITLE
Unstable yaw data

### ISSUE THREAD

**Issue by viatto** [xioTechnologies/Fusion#24]
Hi, I am sorry to bother you again, I am looking to have accurate results in the acceleration data but I found out that the yaw measure is very unstable. I tried to test the device by slowly rotating it to 45 degrees each step and here are the results.
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/100278214/171001683-24b3dc10-ee05-4856-932b-c108835709ba.png">
The rotations of 45 degrees are 3 and have been performed with the same orientation.
I calibrate the magnetometer based on LS ellipsoid fitting of 15000 samples and for the gyroscope and accelerometer just the offset in static conditions obtained by mediating 500 samples. Therefore, I don't think can influence the algorithm.
Can you help me to understand what could be the problem?

**Comment by xioTechnologies** [comment]
The plot suggests that you have the magnetic rejection feature enabled, and that the magnetometer is not providing accurate measurements of magnetic heading.  Please can you disable the magnetic rejection feature in the algorithm settings (i.e. set `magneticRejection` to zero) and share a new plot that includes the magnetometer measurements alongside the Euler angles.  I suggest you perform a 360 degree rotation in fixed steps (e.g. 45 degrees) with a 5 second pause between each step.

**Comment by viatto** [comment]
I read in the documentation that the magnetometer rejection should be at 20, now I have set it to 0.
The result I have obtained is the following:
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/100278214/171023696-4afdb2f3-0410-4a7b-8e23-372585af8025.png">
Seems better but still strange what do you think?

**Comment by xioTechnologies** [comment]
It looks like you have assigned sensor axes incorrectly. What country are you in?  The magnetometer measurements combined with the pitch and roll  indicate a magnetic inclination of around -60 degrees which would put you in either South Africa or Southern Australia.  I think the more likely explanation is that your magnetometer is upside-down and you need to fix the axes assignments.

![image](https://user-images.githubusercontent.com/1748389/171032798-57029258-125c-48e9-b8ff-067bcb6f8989.png)

[The US/UK World Magnetic Model for 2020-2025](http://www.geomag.bgs.ac.uk/documents/WMM2020_Report.pdf)

**Comment by viatto** [comment]
I am in Belgium so yes you are right should be 60 degrees and not -60 degree. How Can I fix the axis? I shoul put the magnetometer down?
![image](https://user-images.githubusercontent.com/100278214/171036004-e639ca0a-58ed-4af6-aff0-d936ec32ce09.png)
This the position of my magnetometer, the z axis is pointing toward the ground

**Comment by xioTechnologies** [comment]
You need to decide what your intended XYZ axis directions are, and then use the sensor measurements that correspond to these directions.

**Comment by viatto** [comment]
Sorry, I don't understand. I have just used the register of the sensor to read the 3 axes data of each integrated sensor and I just supposed that when I compute the fusion update I have the rotation and the acceleration with respect to the reference system of the starting condition which is the one with the x and y-axis parallel to the ground and the z-axis pointing toward the ground. Do I have to develop some function or there is one already implemented in the library?

**Comment by xioTechnologies** [comment]
Your appear to be using the [MPU-9250](https://invensense.tdk.com/products/motion-tracking/9-axis/mpu-9250/).  The device [datasheet](https://invensense.tdk.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf) confirms that the magnetometer axes are not aligned with the gyroscope and accelerometer axes.  The magnetometer is effectively upside-down relative to the gyroscope and accelerometer.

![image](https://user-images.githubusercontent.com/1748389/171057227-c2d38bfc-ad94-41b4-b339-b868022096e3.png)

You must therefore use the following axis assignments when passing the magnetometer values.

`magnetometer = numpy.array([mpu9250_mag_y,  mpu9250_mag_x, -1 * mpu9250_mag_z])`

**Comment by viatto** [comment]
Ok, now I have understood! Thank you so much for your help!

**Comment by RafigRzayev** [comment]
@viatto Hi, in the second chart that you have uploaded, the magnetometer values seem to be in the range [-0.5;1] nT.  The magnetometer values that I get are in the range [-40;40] uT, in other words [-40000;40000] nT. 

To me it looks like there are problems with your raw data too. 

@xioTechnologies Can you confirm please?

**Comment by xioTechnologies** [comment]
I believe that the y axis label is incorrect and that the calibrated magnetometer measurements are normalised for a magnitude of one.  This is common practise because it is usually only the direction of the magnetic field that matters.

**Comment by viatto** [comment]
Yes as you can see from the foto of the datasheet y should be switched with x, also the measurements are normalized to 1 because as @xioTechnologies mention it doesn't matter for attitude the magnitude of the measurement
