### ISSUE TITLE
Strange yaw angle behavior

### ISSUE THREAD

**Issue by RafigRzayev** [xioTechnologies/Fusion#27]
I have previously used the library without magnetometer, and pitch/roll angles are working perfect. 

Now, I am trying to use IMU + magnetometer in order to get yaw angles too.  I am using ExampleAhrs as reference point. The pitch/roll angles are still correct, but the yaw angles are strange. To elaborate:
1) There is no drift in yaw angles, they are pretty stable
2) When I rotate the sensor in yaw direction, I can see the change in yaw angle, but the change is not quite right. For example, when I rotate the sensor 90 degrees, the change in yaw angle that I get is around 60-70 degrees. 
3) The coordinate system of IMU and magnetometer doesn't match, so I modify the magnetometer input accordingly.
![Capture](https://user-images.githubusercontent.com/58329539/157663967-0ba636fb-035f-4f8b-852b-b03890ae54da.JPG)
In my setup, the orientation of dots of ICs match on PCB, so I do the following:
fusion_mag_x = mag_y
fusion_mag_y = - mag_x
fusion_mag_z = - mag_z
4) There may be small misalignment between the IMU and magnetometer axis, but definitely less than 5 degrees. 
5) The raw magnetometer values that I get is usually between [-60uT; 60uT]. I tried to use larger values for magnetic field limits on the function below, but no difference in resut: `FusionAhrsSetMagneticField(&fusionAhrs, 20.0f, 70.0f);`
6) When I rotate the device in yaw dimension and also move it, the yaw angle drifts apart from changing. 
7) I am not doing any kind of calibration on the magnetometer. 

Previously, I have used MPU9250(with internal magnetometer) and a fusion example on Arduino, and the behavior of yaw angles there was exactly the same. 

Is it normal behavior? If not, I would appreciate if you can guide me about where to look for the problem. 
Is magnetometer calibration necessary?

**Comment by shads73** [comment]
I have the same yaw behavior, disproportionate display of the angle of rotation, if you orient to the north, then when yawing the readings are very sensitive, if you turn the direction to the south, the readings change very stretched...

https://github.com/xioTechnologies/Fusion/issues/25
Here they say that it is necessary to calibrate, I am also now engaged in screwing the frescale calibration function

I hope after calibration the yaw range will become proportional ...

**Comment by xioTechnologies** [comment]
Magnetometer calibration is essential for meaningful measurements of heading.

**Comment by RafigRzayev** [comment]
Thank you, I will try calibration and let you know.

**Comment by RafigRzayev** [comment]
@shads73 I tried following [instructions ](https://appelsiini.net/2018/calibrate-magnetometer/)for the calibration, results are now much better. I am now able to detect 90 degree rotations. But there are still few problems:
1) When I rotate 90 degrees slowly, the resulting change is not correct (again 60 degreees). 
2) And when I change pitch/roll, yaw also changes. 

When I plotted the raw magnetometer data, it was following:

![cap1](https://user-images.githubusercontent.com/58329539/157837283-0996b999-f57c-4afb-b895-318c41a56c59.JPG)

It is clear that there is both offset(hard-iron) and elliptic shape(soft-iron). 

Following the instructions led to these calibrated results:
![cap2](https://user-images.githubusercontent.com/58329539/157837572-5a691ef9-f387-40ef-8d76-0a30baafa535.JPG)

The offset is now eliminated, but the elliptical shape is still present. I believe I need to use matrix transformation approach to eliminate soft-iron distortion. 

I'll share future updates.

**Comment by shads73** [comment]
> 2. And when I change pitch/roll, yaw also changes.

I think your problem is that you are using the Z axis incorrectly, I have not found a mention anywhere that the Z axis is directed down, and for me it is not inverted, your Z axis is inverted ... I think this is the problem. try to fix it like this 
fusion_mag_x = mag_y
fusion_mag_y = - mag_x
fusion_mag_z = mag_z

**Comment by RafigRzayev** [comment]
By the way I tried to increase dataset for the calibration, now corrected data looks much better. Also, in the previous post, I was incorrect about it having elliptical shape after calibration, it looks such because of plotter scale difference between horizontal and vertical lines. These are the new plots:
Raw data:
![raf1](https://user-images.githubusercontent.com/58329539/157867755-9e697701-e421-4feb-8b81-eb285a0ca117.JPG)
Calibrated data:
![raf2](https://user-images.githubusercontent.com/58329539/157867766-3d4db3cc-330e-4ae6-b64f-a228708de324.JPG)
Calibrated data:
![good](https://user-images.githubusercontent.com/58329539/157867997-1712cf48-be90-4f4d-87c7-6cc09bf6dfa0.JPG)

So, I guess the calibration seems fine at the moment. Some strange behavior of angles continues, I am still looking into it. 

As for z axis inversion, if you look to those illustrations, you can see that for the ICM Z axis looks top, while for the magnetometer it looks down. That's why I inverted them.

**Comment by shads73** [comment]
Where did you get this illustration of a magnetometer with the z-axis turned down?
I searched and did not find any mention of the fact that the Z axis is turned down.
Can you give me a link to a resource with this illustration?

**Comment by RafigRzayev** [comment]
I believe the orientations may differ based on the manufacturer. I am using following:
Magnetometer: [MMC5983MA](http://www.memsic.com/uploadfiles/2021/12/20211202135252941.pdf)
IMU: [ICM-42670-P](https://3cfeqx1hf82y3xcoull08ihx-wpengine.netdna-ssl.com/wp-content/uploads/2021/07/DS-000451-ICM-42670-P-v1.0.pdf)

This screenshot is based on these datasheets(p9 and p18 respectively), you can see that they are inverse for these models. But again final orientation depends on how you put them on PCB with respect to each other.
![Capture](https://user-images.githubusercontent.com/58329539/157876205-83cf163e-9067-466d-a8d8-5d818a623182.JPG)

**Comment by shads73** [comment]
Really...
I looked at the datasheet for HMC5983, but there does not explicitly indicate the direction of the Z axis
Suspiciously, these two chips are very similar, but I have the Z-axis turned up. If I invert the Z-axis data like you have, then the yaw starts responding to roll changes.

**Comment by RafigRzayev** [comment]
I checked the HMC datasheet. I believe they didn't mention z axis explicitly. But if you pay attention to below image, you can see a dot symbol
![hmc](https://user-images.githubusercontent.com/58329539/158019913-1838e040-040e-4408-951b-73452941957a.JPG)
For magnetic field, dot sign means direction out of page. Image from this [link](http://physicsed.buffalostate.edu/SeatExpts/resource/rhr/rhr.htm): 
![mag](https://user-images.githubusercontent.com/58329539/158019945-5dcfedae-b83c-4d5f-a0d3-ab883279ff82.JPG)

Since it is top view, z axis aims top in your case. For my magnetometer, it is inverse.

**Comment by xioTechnologies** [comment]
If you are unsure what direction an axis is then I suggest you plot the sensor output while rotating it around an axis orthogonal to the axis of interest.  The output plot will peak when the axis is facing north.

I recommend you use the [x-IMU3 GUI](https://x-io.co.uk/x-imu/#downloads) to plot the real-time data.  You will need to modify your firmware to output the magnetometer data by serial as the ASCII string: `M,123,4,5,6\r\n` where `123` is a counter that increments with each message sent, `4` is the x axis value, `5` is the y axis value, and `6` is the z axis value.  You open the serial port as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/1748389/158021156-94dd1f64-5254-4d03-a253-92f38a9c28cb.png)

![image](https://user-images.githubusercontent.com/1748389/158021172-1d157222-1dbc-4ee0-9eeb-eec4b453d017.png)

You can use this software to plot an visualise other sensors and 3D orientation.  Just follow the communication protocol in the user manual.

**Comment by shads73** [comment]
> If you are unsure what direction an axis...
No more questions...

everything is already clear!
HMC5983 sensor has Z axis pointing up
MMC5983 sensor has Z axis pointing dn

although they look like two drops of water) ...
(other than Z axis direction)

**Comment by shads73** [comment]
@RafigRzayev Thanks for your notes, I learned valuable information!

**Comment by RafigRzayev** [comment]
I believe my problem is that the raw magnetometer data is also changing when I move the device in same direction. Furthermore, It jumps when near laptop, on the table, depending on location inside the room. It seems to me that it is environmental noise that affects it. 

According to this behavior, it seems to me that magnetometer cannot be utilized for a wearable device. 

But on the other hand, phones are using magnetometers...

**Comment by shads73** [comment]
I think this is natural when there are massive objects, reinforced concrete structures or something else that changes the picture of the earth's magnetic field near the magnetometer - this will affect the readings of the magnetometer.
I think that with each change of location (if we are indoors), it is necessary to calibrate the magnetometer for satisfactory operation, otherwise the behavior will be unpredictable.
For example, my device senses a compasses caliper, which I place at a distance of 50 cm. The magnetometer is a very sensitive device and reacts to the slightest changes in the magnetic field.
My device will be used outdoors, so it's easier for me)

**Comment by RafigRzayev** [comment]
Hmm interesting.  

In my application, I was expecting to calibrate device once, and then use it freely anywhere (in the building, car, subway, outdoors and etc.). Recalibration often is not an option for my case. 

I believe then I won't be able to calculate yaw angles. 

But still I am not 100% confident. I believe phones are working good in this sense, how come they don't get affected.

**Comment by RafigRzayev** [comment]
Thank you very much for clarification. 

Then magnetometer is not suitable for my use case.
