### ISSUE TITLE
Use fusion output to determine rotation along local axis

### ISSUE THREAD

**Issue by theol0403** [xioTechnologies/Fusion#27]
Hello,

I am using this library for a project, but I am having trouble figuring out how to manipulate the output quaternions.

This issue is not specific to this project, so if I should ask somewhere else like stackoverflow, please close this issue. However, I am asking because this functionality might be useful to include in the library.

Essentially, I am only interested in rotation along a local axis of my gyro, specifically the z axis. I started by manually integrating the z gyro output to get angle, which is the format of the data I want. However, there was drift, and I wanted to use a proper sensor fusion algorithm to include the accelerometer. That way, if the sensor is spinning vertically, it can use gravity to prevent drift.

I switched to using this library, and it works amazingly well at giving me a global rotation quaternion. However, I am not sure how to go from a global quaternion back to the local rotation along the z axis. I want the values to not be constrained +-180 because I want to use them to count rotations.

To attempt to solve this, I started by identifying the direction of the local z axis in the global frame:

```c
quat = FusionAhrsGetQuaternion(&ahrs);
direction = FusionVectorNormalise(FusionMatrixMultiplyVector(FusionQuaternionToMatrix(quat), {{0.0, 0.0, 1.0}}));
```

Then, my question can be re-stated as "what is my rotation along this axis". However, here I am stuck, and I am also not sure if this is the correct approach at all, especially if I want unbounded angles. 

Thanks!

**Comment by xioTechnologies** [comment]
As you say, this question belongs in another forum.  You may wish to try XYZ Euler angles.  The final rotation is a rotation around the local Z axis.
