### ISSUE TITLE
Rotation of global acceleration

### ISSUE THREAD

**Issue by viatto** [xioTechnologies/Fusion#28]
Hi, I am using your library to obtain the acceleration in a global reference frame considered as the initial position of my sensor. So in order to remove the initial rotation of the yaw angle given by the magnetic field, I rotate my acceleration vector of this angle:
`            linacc[0] = linacc[0] * math.cos(angle ) - linacc[1] * math.sin( angle)
              linacc[1] = linacc[0] * math.sin(angle ) + linacc[1] * math.cos( angle) `
Unfortunately, This does not solve the problem can you help to understand the problem? I noticed that if I just translate the sensor in the XY plane, without any rotation, I obtain instability in the yaw measurements.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/100278214/173179141-9bd26920-06a4-4bc5-ab2c-fc9b22f60558.png">
 Am I doing something wrong?
This is the code I am using:
`        g = offset.update(g)
        ahrs.update(g, a, MagVals, deltat)
        euler = ahrs.quaternion.to_euler()
        linacc= ahrs.earth_acceleration
        linacc= linacc * 9.81
`
This is the initialization of the algorithm:
`offset = imufusion.Offset(100) #sample rate
ahrs = imufusion.Ahrs()
ahrs.settings = imufusion.Settings(0.5,  # gain
                                   10,  # acceleration rejection
                                   0,  # magnetic rejection
                                   500)  # rejection timeout = 5 seconds`

I tried also with a higher sample rate (180 Hz) and I have better results in the rotation but still unstable yaw.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/100278214/173179496-23dc422d-fe3e-4132-909c-af118c3fedac.png">

**Comment by xioTechnologies** [comment]
I suspect that the issue is poor magnetometer calibration.  I suggest you use `ahrs.update_no_magnetometer` instead of `ahrs.update` so that the magnetometer is ignored.  If you are using the algorithm without the magnetometer then you can use the `ahrs.heading = 0` to zero the yaw at any time.

**Comment by viatto** [comment]
it is not working the function ahrs.update_no_magnetometer

**Comment by xioTechnologies** [comment]
Please provide a description of the issue

**Comment by viatto** [comment]
`ahrs.update_no_magnetometer(g1, a1, deltat)` If I try to substitute in the code this function instead of the  classic one  'ahrs.update'. The only result I have in acceleration function `ahrs.earth_acceleration` is a vector of 0 , 0, 1

**Comment by xioTechnologies** [comment]
The code and plot below does not demonstrate the issue you have reported.  I believe the problem is with either your data or your use of the library.  I suggest you start from a working example and make small iterative changes towards your intended design.

```python
import imufusion
import matplotlib.pyplot as pyplot
import numpy

data = numpy.genfromtxt("sensor_data.csv", delimiter=",", skip_header=1)

gyroscope = data[:, 1:4]
accelerometer = data[:, 4:7]

ahrs = imufusion.Ahrs()
earth_acceleration = numpy.empty_like(gyroscope)

for index in range(len(gyroscope)):
    ahrs.update_no_magnetometer(gyroscope[index], accelerometer[index], 1 / 100)
    earth_acceleration[index] = ahrs.earth_acceleration

pyplot.plot(earth_acceleration)
pyplot.show()
```
![image](https://user-images.githubusercontent.com/1748389/174494137-f587ccc5-bb28-4fd3-be23-17cea663e4dc.png)
