### ISSUE TITLE
Is it possible to use with multiple IMU sensors?

### ISSUE THREAD

**Issue by ibrahimcahit** [xioTechnologies/Fusion#28]
Hi, 

I have got an MPU9250 9DoF sensor, which is working well with this fusion algorithm. I also have MPU6050 6DoF IMU sensor.

Is it possible to combine fusion algorithm for this two sensors? To achive single pitch - yaw - roll output by using two IMU sensors?

**Comment by xioTechnologies** [comment]
Fusion does not offer any tools for combining data from multiple sensors of the same type.

**Comment by ibrahimcahit** [comment]
Any suggestions about how to do it? or recommendations?
