### ISSUE TITLE
The results of X-aix and Z-axis are affected by Y-axis

### ISSUE THREAD

**Issue by JackHenry1992** [xioTechnologies/Fusion#31]
Thanks for sharing your great job!
In practice, I only rotate the Y axis, but the results of X-axis and Z-axis will also output values, which means that Pitch and Yaw values are affected by the Y-axis.
![image](https://user-images.githubusercontent.com/9390228/173424168-37259247-23f3-4fd1-b445-d99c95d24976.png)

The gyroscope value as follows:
![image](https://user-images.githubusercontent.com/9390228/173424652-f3efe2e2-c751-448a-b508-5fb64c6235aa.png)

Is there something wrong in my case? I record the data using a samsung mobile phone.

**Comment by xioTechnologies** [comment]
Your top graph is mislabelled, you need to swap "Pitch" and "Roll".  The issue you are observing is a well-known problem with Euler angles, commonly referred to as [gimbal lock](https://en.wikipedia.org/wiki/Gimbal_lock).

**Comment by JackHenry1992** [comment]
Do you mean that I need to modify the function of `ahrs.quaternion.to_euler()`?

**Comment by xioTechnologies** [comment]
No, I am saying that this is just how Euler angles behave.  I suggest you search online to learn more.

**Comment by JackHenry1992** [comment]
Thx for your kind reply.
