### ISSUE TITLE
acceleration units

### ISSUE THREAD

**Issue by AmbatiThrinay** [xioTechnologies/Fusion#38]
can you please mention the acceleration units for  the functions :

- FusionAhrsGetEarthAcceleration( )
- FusionAhrsGetEarthAcceleration( )

one more thing, thanks for the great library 👌.

**Comment by xioTechnologies** [comment]
Thank you for the suggestion.  The units were added to `FusionAhrsGetLinearAcceleration` and `FusionAhrsGetEarthAcceleration` in commit 689ce087ede77bb6e703d7491eba27a3146cd301.  This will be merged in the next few days.

**Comment by xioTechnologies** [comment]
The commit as been merged in 4b71f139baa7b1865240e9c438448efcfe755dde.
