### ISSUE TITLE
Somewhat confused by the Euler angle conversion

### ISSUE THREAD

**Issue by kamnxt** [xioTechnologies/Fusion#48]
Hi!

I'm having some issues with understanding the relation between the imu input axes and the euler angles from the resulting quaternion.
Here's an example: I have equal acceleration in the Y and the Z axis. I would guess that in this case I should be getting 45 degrees of pitch, but instead I am getting 45 degrees of roll? I was expecting to have Z upwards, X to the side and Y in the front/rear axis, but it seems that isn't the case here?

```
#include "Fusion/Fusion.h"
#include <stdio.h>

int main() {
	FusionAhrs ahrs;
	FusionAhrsInitialise(&ahrs);
	for(int i = 0; i < 100; i++) {
		FusionVector acc, gyr;
		acc.axis.x = 0;
		acc.axis.y = 1;
		acc.axis.z = 1;
		gyr.axis.x = 0;
		gyr.axis.y = 0;
		gyr.axis.z = 0;
		FusionAhrsUpdateNoMagnetometer(&ahrs, gyr, acc, 0.01);
	    FusionEuler eul = FusionQuaternionToEuler(FusionAhrsGetQuaternion(&ahrs));
	    printf("p,r,y = %.3f, %.3f, %.3f\n", eul.angle.pitch, eul.angle.roll, eul.angle.yaw);
            //prints p,r,y = 0.000, 45.012, 0.000
	}
}
```

**Comment by xioTechnologies** [comment]
The Euler angle [documentation](https://github.com/xioTechnologies/Fusion/blob/main/Fusion/FusionMath.h#L68) states, "_Roll, pitch, and yaw correspond to rotations around X, Y, and Z respectively._".  The behaviour you have described is consistent with the documentation.

**Comment by kamnxt** [comment]
I see, so Fusion uses the "x forwards/backwards, y to the sides, z up/down" convention like used for [aircraft](https://en.wikipedia.org/wiki/Axes_conventions#Conventions_for_aircraft_local_reference_frames), now things make much more sense. Was looking at things from a computer graphics / 3d game engine perspective where x is to the side, y is forwards/backwards and z is up/down, and things weren't making much sense. Maybe it could be possible to mention that this is the convention used somewhere in the readme?

**Comment by xioTechnologies** [comment]
The [README](https://github.com/xioTechnologies/Fusion#readme) already states, "_The quaternion describes the orientation of the sensor relative to the Earth using the North-West-Up (NWU) convention._".  That is, X = North, Y = West, Z = Up.

**Comment by kamnxt** [comment]
Ah, must have missed it when looking for it... Thank you for the quick replies, closing this.
