### ISSUE TITLE
Orientation is not stable

### ISSUE THREAD

**Issue by rohithr2597** [xioTechnologies/Fusion#49]
Hi. I am trying to visualize the orientation using the x-IMU3 GUI. The orientation is stable with small drfit when the beta value is 0.033 but then if I rotate and then comeback to the initial position it takes lot of time to update. When I Increase the beta value the drift increases and the update rate seems to be high. The acclerometer and magnetometer data is stable whereas gyro has noise. Do you have any suggestions?

I am using MadgwickAHRS.c file to get the quaternion data.
sampling rate: 1024 HZ

**Comment by xioTechnologies** [comment]
The code you are using is not from this repository.  I suggest you use [Fusion](https://github.com/xioTechnologies/Fusion) (this repository).
