### ISSUE TITLE
Control flow error in `FusionAhrsUpdate`

### ISSUE THREAD

**Issue by r8d8** [xioTechnologies/Fusion#50]
Update function checks acceleration/magnetometer rejection time against rejection timeout form setting,
as follows for accelerometer:
```
if (ahrs->accelerationRejectionTimer > ahrs->settings.rejectionTimeout) {
            const FusionQuaternion quaternion = ahrs->quaternion;
            FusionAhrsReset(ahrs);
            ahrs->quaternion = quaternion;
            ahrs->accelerationRejectionTimer = 0;
            ahrs->accelerationRejectionTimeout = true;
        }
```
later in this funciton exist check with magic number "10":
```
ahrs->accelerationRejectionTimer -= ahrs->accelerationRejectionTimer >= 10 ? 10 : 0;
```
In case if ahrs->settings.rejectionTimeout more than "10" we won't  never get inside `if`
Same happens for magnetometer.

**Comment by xioTechnologies** [comment]
The value 10 is described in documentation, I do not think it is fair to call this a magic number.  The [README](https://github.com/xioTechnologies/Fusion#readme) states, "_An acceleration rejection timeout occurs when the number of algorithm updates that have ignored the accelerometer exceeds **ten** times the number that have used the accelerometer within a defined period._".

"_in case if ahrs->settings.rejectionTimeout more than "10" we won't never get inside if_" - this claim is demonstrably not true.  [advanced_example.py](https://github.com/xioTechnologies/Fusion/blob/main/Python/advanced_example.py) uses a `rejectionTimeout` value of 500 and so already disproves the claim.

**Comment by r8d8** [comment]
there is check for magnetometer (and same for accelerometer):
```
if (ahrs->magneticRejectionTimer > ahrs->settings.rejectionTimeout) {
...
```
But in setting `rejectionTimeout` specified as:
```
// Set AHRS algorithm settings
    const FusionAhrsSettings settings = {
            .gain = 0.5f,
            .accelerationRejection = 10.0f,
            .magneticRejection = 20.0f,
            .rejectionTimeout = 5 * SAMPLE_RATE, /* 5 seconds */
    };
```
(SAMPLE_RATE in example is 100, so rejectionTimeout will be 500)
And then algorithm align RejectionTimers as:
```
ahrs->magneticRejectionTimer -= ahrs->magneticRejectionTimer >= 10 ? 10 : 0;
```
So `ahrs->magneticRejectionTimer > ahrs->settings.rejectionTimeout` is will be false allways, as you get compare 0..10 with 500

It's not `10 times` its just 10

**Comment by xioTechnologies** [comment]
I suggest you test your claim by running the code with the data provided, using [advanced_example.py](https://github.com/xioTechnologies/Fusion/blob/main/Python/advanced_example.py).  You will see that your claim is not true.

**Comment by r8d8** [comment]
I already made it, with data recorded from Pololu IMUv10 10Dof sensor

**Comment by xioTechnologies** [comment]
Your analysis of the code is incorrect.  Your claim is disproven by running [advanced_example.py](https://github.com/xioTechnologies/Fusion/blob/main/Python/advanced_example.py).  I have invited you to do this three times now.  I would like for you to do this so that you see your mistake and then have an opportunity to ask clarifying questions.  If you are not willing to engage then I will close this issue.
