### ISSUE TITLE
Question: about the imu data(acc, gyro, mag)  which is desynchronized

### ISSUE THREAD

**Issue by mingrenzhu** [xioTechnologies/Fusion#52]
hello, I have a  question about " can the fution algorithm process the desynchronized imu data ? ", thanks a lot.

**Comment by xioTechnologies** [comment]
If your sensor measurements are not synchronised then you would call `FusionAhrsUpdate` for each new gyroscope measurement, with with most recent measurements from the other sensors.

**Comment by mingrenzhu** [comment]
well, i wonder whether i can do this, i call **FusionAhrsUpdate** for the new gyroscope, and if gyroscope time is large with acc and mag time, than can i set the acc and mag as zeros vector ? 
thank you and hope your reply, cheers!

**Comment by xioTechnologies** [comment]
You should use the latest accelerometer and magnetometer measurements, even if that means reusing measurements.  You should not pass in zero vectors.

**Comment by mingrenzhu** [comment]
Got it, thanks a lot.
