### ISSUE TITLE
question: about quaternion usage convention based on JPL or Hamilton in Fusion project ?

### ISSUE THREAD

**Issue by mingrenzhu** [xioTechnologies/Fusion#54]
In your code the "halfGravity" vector is computed using JPL convention. which is the same as the [Madgwick's PhD thesis](https://ethos.bl.uk/OrderDetails.do?uin=uk.bl.ethos.681552) , the related math is shown as follows,
![image](https://user-images.githubusercontent.com/37427077/202139522-bf366620-9c29-4438-8a66-46911c0d4dc1.png) However, when computing the euler angle from the quaternion pose,  the corresponding function code named by "FusionQuaternionToEuler"  is different from Madgwick's paper(in the paper, roll = atan2(2(q_y*q_z - q_w* q_x)... but in your code roll=atan2(2(q_y*q_z + q_w* q_x)... are they the same?
![image](https://user-images.githubusercontent.com/37427077/202140598-4cc62043-8181-4e71-ab39-50d62ccbf99f.png)

**Comment by xioTechnologies** [comment]
The potential inconsistency between the quaternion to rotation matrix, and quaternion to Euler angle conversions was already investigated in detail, and resolved in issue #9.
