### ISSUE TITLE
Calibration in IMU library or Fusion?

### ISSUE THREAD

**Issue by LazaroFilm** [xioTechnologies/Fusion#59]
I am using Fusion on an Arduino Nano 33 BLE. The IMU library, I am using a [library](https://github.com/FemmeVerbeek/Arduino_LSM9DS1) that has sensor calibration and correction with a calibrate output option and a raw output option. It also has calibration scripts for all sensors. Should I use the pre-calibrated output to send to Fusion? Or should I use the raw output and have Fusion use its calibration (I believe I can adapt the calibration scripts data from the IMU library to Fusion). Thanks!

**Comment by xioTechnologies** [comment]
Accurate measurements are always preferable over less accurate measurements.  If you are able to provide calibrated measurements, then use those.
