### ISSUE TITLE
Chaining fusion filter and tilt-compensated compass heading

### ISSUE THREAD

**Issue by ozolli** [xioTechnologies/Fusion#6]
Hi,

I have no problem using the fusion filter functions or the tilt-compensated compass heading function but I cannot see how to chain them, sending the result of the filter (quaternion, matrix or euler angles) to the FusionCompassCalculateHeading function which needs vectors as input.

I must miss something as an AHRS newbie... Is there a way to achieve this or the other way around maybe : tilt-compensate then send to filter ?

Thank you in advance for your answer.

Olivier.

**Comment by xioTechnologies** [comment]
The AHRS algorithm and tilt-compensated compass function are not intended to be chained.  Please see the latest examples demonstrating the the typical use cases of the library.
