### ISSUE TITLE
Understanding FusionMatrix gyroscopeMisalignment

### ISSUE THREAD

**Issue by LazaroFilm** [xioTechnologies/Fusion#65]
When I rotate my sensor around the Z axis (on a turntable), I get the below graphs which shows some wobble in the roll and pitch with `.gain` to set to `0.0f` to ignore accel input.
I think I understand this "wobble" is due to a gyro axis misalignment. I'm trying to understand how the `FusionMatrix` works, but I'm not quite sure of the method to get the values needed for it. I understand each values is a multiplier to add some of the other axis input in another one, but I don't know how to tell which value and by how much... I've found [this article](https://www.analog.com/en/analog-dialogue/articles/mems-imu-gyroscope-alignment.html) but it hasn't quite helped me that much.
 
![Matrix initial](https://user-images.githubusercontent.com/18351100/215578116-f05b14cc-00b0-46d8-a4bf-35885e0b623f.jpg)

and zoomed in version to focus on pitch and roll, recorded here are two full rotation so 720deg rotation it was turned by hand on a solid center axle, hence the roughness of the curve. I'm also aware of the gyro drift. I recorded this example right after powering up the IMU, it had not stabilized yet: 

![Matrix initial zoomed in](https://user-images.githubusercontent.com/18351100/215578119-b889d25e-00d2-4fb6-a66e-fc5f81071082.jpg)

**Comment by xioTechnologies** [comment]
We do not have any tutorials or examples for the calculating a misalignment matrix.  The [article](https://www.analog.com/en/analog-dialogue/articles/mems-imu-gyroscope-alignment.html) you linked looks like a good place to start.

On a separate note, I suggest you use the gyroscope offset correct algorithm as demonstrated on [line 24](https://github.com/xioTechnologies/Fusion/blob/main/Examples/Advanced/main.c#L24) and [line 51](https://github.com/xioTechnologies/Fusion/blob/main/Examples/Advanced/main.c#L51).  Adding these two lines of code will correct for the drift apparent in your plots.

**Comment by herbertvuijk** [comment]
This guy made a calibration that is very similar to the misalignment matrix used by the xio Fusion algo. It's for an accelerometer though, but I guess the principles are the same.

By the way I found out by testing that you indeed have to do like a 6-orthogonal calibration for the accelerometer as offsets and gains are different in every position. A gyroscope though, seems to have the same offsets regardless of orientation. So I guess you don't really need a misalignment gyromatrix. Instead you can just substract a constant value that you have measured. 

Here an example of a calibration matrix (offset, gain, angles): 

https://github.com/BasicAirData/Clinometer/blob/master/app/src/main/java/eu/basicairdata/clinometer/CalibrationActivity.java
