### ISSUE TITLE
No matching distribution found for imufusion, Arm, Raspberry Pi 

### ISSUE THREAD

**Issue by DandrewsDev** [xioTechnologies/Fusion#7]
I would love to use this for a project Im working on, but does not seem like there is any support for Pi boards right now.

When I try to run "pip install imufusion" it errors out 
ERROR: Could not find a version that satisfies the requirement imufusion
ERROR: No matching distribution found for imufusion

After digging adding the -v flag and digging into the output it appears to be because there is currently no Arm support. Is something like that possible?

**Comment by xioTechnologies** [comment]
The Python package installed using `pip install` is limited to the platforms supported by [GitHub Actions Runner](https://github.com/actions/runner).  If your platform is not supported then you can run [setup.py](https://github.com/xioTechnologies/Fusion/blob/main/Python/Python-C-API/setup.py) to build and install the package on your target platform.

**Comment by DandrewsDev** [comment]
Was able to build and use the package locally. Adding the steps I needed to follow below incase anyone else ever runs into this.

Ran into errors using numpy from pip on raspberry pi. 
Thats fixable following the steps here https://numpy.org/devdocs/user/troubleshooting-importerror.html
1. pip3 uninstall numpy  # remove previously installed version
2. sudo apt install python3-numpy

1. Clone repo
2. cd Fusion/Python/Python-C-API
3. python3 setup.py
4. cd dist
5. unzip imufusion-1.0.1-py3.9-linux-armv7l.egg
6. cp imufusion.cpython-39-arm-linux-gnueabihf.so and imufusion.py to project libraries
7. import numpy, imufusion

And now its working great. Thanks for the info.

**Comment by bshmid** [comment]
> The Python package installed using `pip install` is limited to the platforms supported by [GitHub Actions Runner](https://github.com/actions/runner). If your platform is not supported then you can run [setup.py](https://github.com/xioTechnologies/Fusion/blob/main/Python/Python-C-API/setup.py) to build and install the package on your target platform.

Hello,
I had downloaded setup.py and placed it in Fusion-main directory, as I run it I get the following message:
`running install
running bdist_egg
running egg_info
creating imufusion.egg-info
writing imufusion.egg-info/PKG-INFO
writing dependency_links to imufusion.egg-info/dependency_links.txt
writing top-level names to imufusion.egg-info/top_level.txt
writing manifest file 'imufusion.egg-info/SOURCES.txt'
reading manifest file 'imufusion.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'imufusion.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_ext
building 'imufusion' extension
creating build
creating build/temp.linux-armv7l-3.10
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/pi/.local/lib/python3.10/site-packages/numpy/core/include -I/usr/local/include/python3.10 -c ../../Fusion/FusionAhrs.c -o build/temp.linux-armv7l-3.10/../../Fusion/FusionAhrs.o
gcc: error: ../../Fusion/FusionAhrs.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1


------------------
(program exited with code: 1)
Press return to continue
`
The file FusionAhrs.c is there in Fusion sub directory but I don't know what the rest of the path should be.
Thank you in advance.

**Comment by xioTechnologies** [comment]
> I had downloaded setup.py and placed it in Fusion-main directory...

Why are you rearranging the files?  You should download the whole repository and run setup.py as it is.

**Comment by bshmid** [comment]
> Why are you rearranging the files? You should download the whole repository and run setup.py as it is.
Thank you very much!
I just did not know it was there.
Now it works.
