### ISSUE TITLE
Bug - Commit "Use designated initialisers" breaks compilation in C++

### ISSUE THREAD

**Issue by ladislas** [xioTechnologies/Fusion#77]
Downloading the latest source from main, it seems that https://github.com/xioTechnologies/Fusion/commit/ec507511cff0e7499e38f54f0e4eaa5abeffa99e introduced a bug when working in C++.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2206544/217490271-5d8de309-9aa0-4889-b0df-c44df93c72cd.png">

**Comment by xioTechnologies** [comment]
Please can you confirm which compiler you are using.  Please can you also show me how you include Fusion in your .cpp files.  You should only use `#include "Fusion.h` because this file wraps the library in `extern "C"`.

**Comment by ladislas** [comment]
> Please can you confirm which compiler you are using

```
arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

> Please can you also show me how you include Fusion in your .cpp files

Here: https://github.com/leka/LekaOS/blob/ladislas/feature/replace-mahony-with-new-fusion/libs/IMUKit/source/IMUKit.cpp#L13

**Comment by xioTechnologies** [comment]
We are investigating this.  In the mean time, please either use the [latest version](https://github.com/xioTechnologies/Fusion/releases/tag/v1.0.7), or revert https://github.com/xioTechnologies/Fusion/commit/ec507511cff0e7499e38f54f0e4eaa5abeffa99e to avoid the issue.

**Comment by xioTechnologies** [comment]
The issue should be fixed as of https://github.com/xioTechnologies/Fusion/commit/dde922f72a717aa251ee1c18d242f57bb6bc2de2.  Please can you confirm the fix on your system.

**Comment by ladislas** [comment]
I can confirm that the issue has been fixed, thanks a lot!
