### ISSUE TITLE
FusionCalibrationInertial vs FusionOffsetUpdate

### ISSUE THREAD

**Issue by ladislas** [xioTechnologies/Fusion#79]
In our project, we've implemented the [Advanced](https://github.com/xioTechnologies/Fusion/blob/main/Examples/Advanced/main.c) example provided, that you can see here:

https://github.com/leka/LekaOS/blob/develop/spikes/lk_sensors_imu_lsm6dsox_fusion_calibration/main.cpp

We have followed the following protocol:

**1. Calculate static accel + gyro offsets**

- log raw accelerometer + gyroscopes values **without** calibration
- record the values for 2min using x-IMU3 software
- calculate the average of the values to get the offset for each axis

**2. Apply previously obtained offsets**

Using then apply the offsets using [`FusionCalibrationInertial`](https://github.com/leka/LekaOS/blob/41f3e6c652fc5740d3dfe61fc7b92270bd6612f9/spikes/lk_sensors_imu_lsm6dsox_fusion_calibration/main.cpp#L76-L80).

As a side note, only using `FusionCalibrationInertial` reduces the yaw drift greatly.

**3. Apply runtime gyroscope offset correction**

Using [`FusionOffsetUpdate`](https://github.com/leka/LekaOS/blob/41f3e6c652fc5740d3dfe61fc7b92270bd6612f9/spikes/lk_sensors_imu_lsm6dsox_fusion_calibration/main.cpp#LL83C16-L83C34) we apply runtime calibration to the gyroscope, as explained [here](https://github.com/xioTechnologies/Fusion#gyroscope-offset-correction-algorithm)

---

During code review, one our team member tried using **only** `FusionOffsetUpdate` **without** using `FusionCalibrationInertial`.

He said the effect seemed to be the same: reduce yaw drift to almost zero giving us stable values over time when the device is not moving.

He then asked the following question:

> What's the difference between the two? Why do we need both? Would using `FusionOffsetUpdate` be enough?

My answer was "trust the experts and follow the canonical example first, before trying to do things differently. Then we can experiment".

But I was not happy with my answer, so I'd like to add more information.

What would you say in that situation?

**Comment by xioTechnologies** [comment]
As stated in the [README](https://github.com/xioTechnologies/Fusion/blob/main/README.md), "_the gyroscope offset correction algorithm provides run-time calibration of the gyroscope offset to compensate for variations in temperature and fine-tune existing offset calibration that may already be in place_".  The inertial calibration model just subtracts whatever offset is specified by the user, usually a constant value.
