### ISSUE TITLE
Suitable magnitude filter?

### ISSUE THREAD

**Issue by Lelelo1** [xioTechnologies/Fusion#8]
I have some questions regarding the magnitude filter. First of all is it truly clear that a magnitude that deviates from earth's magnetic field magnitude creates a faulty compass heading? If so is there any more information on that somewhere? And assuming it is correct - what would a suitable magnitude filter be?

**Comment by xioTechnologies** [comment]
I suggest you use the latest version of the algorithm: https://github.com/xioTechnologies/Fusion

**Comment by xioTechnologies** [comment]
My previous response was in error, I thought your issue was posted in a different repository.

I assume that you are referring to the min/max valid magnetic field values when you say "magnitude filter".

A heading calculation is not affected by the magnitude of a magnetic field, only the direction.  It is possible for a measured magnetic field to be that of the Earth plus an interfering magnetic field with a direction equal to that of the Earth's magnetic field.  In this situation the measured magnetic field would result in an accurate heading measurement even though the magnitude of the measured magnetic field has deviated from that of the Earth's magnetic field.  However, this situation is very unlikely to occur.

Suitable min/max valid magnetic field values would be equal to the expected measured magnitude of the Eath's magnetic field plus/minus the expected error in this measurement.

**Comment by Lelelo1** [comment]
Yes I was indeed referring to the min/max magnetic field values.

I see. But while a heading can be correct when the magnetic field deviates from that of earths (being very unlikely as you say) - it can't be incorrect when it is that of the earths. Is that a correct assumption?

Also, if I would disturb the magnetometer sensor in the exact same way, somewhere near the poles - and near the equator. Would the +- measurement deviation from that of earths magnetic field in these locations be same?

**Comment by xioTechnologies** [comment]
It is possible for the magnitude of the measured magnetic field and Earth's magnetic field to be equal and for the heading to be incorrect.  The error would be 180 degrees.  This situation occurs if there is an interfering magnetic field with a direction exactly opposite, and a magnitude exactly double, that of the Earth's.  This is also very unlikely to occur.

The magnitude of the Earth's magnetic field varies with location even for a fixed latitude.  A polar or equatorial location would have no particular relevance to magnetic field magnitude circulations.

**Comment by Lelelo1** [comment]
Ok. But if I take the geomagnetic field given by location with [the geomagnetic model](https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#igrfwmm). And I disturb the sensor in the same way in two locations. Will I get the same +- deviation value in μT from what is given by the geomagnetic model in those locations? Or will it be different? (I thought earths magnetic field was weakest around the equator - but thank you for the correction).

**Comment by xioTechnologies** [comment]
I do not know what you mean by "disturb the sensor", I interpret this to mean a "+- deviation value in μT".  I did not say that there is no correlation between the magnitude of the Earth's magnetic field and latitude.

**Comment by Lelelo1** [comment]
With "disturbing the sensor" I mean holding a piece of metal near the (magnetometer) sensor.

Basically, if the earths magnetic field is 40μT in one location. If I put my metal object 10 centimetres away from the magnetometer by 180 degree and the measured magnetic field then becomes 55μT. Will the measured magnetic field then become 65μT in another location where earths magnetic field is 50μT - if I put the same metal objects 10 centimetres - in the same orientation.

**Comment by xioTechnologies** [comment]
Metal objects can create hard-iron distortions (offsets errors) and soft-iron distortions (scaling and axes-coupling errors).  If your metal object creates only hard-iron distortions then this will result in the observations you have described.  However. if your metal object also creates soft-iron distortions then the errors will be more complex.

**Comment by Lelelo1** [comment]
Does soft iron distortion affect the total magnetic field as well?

**Comment by xioTechnologies** [comment]
I suggest you search on-line to get a better understanding of magnetic distortions and magnetometer calibration.

**Comment by Lelelo1** [comment]
From my current experience using deferring by norm seem useless. For me it was roughly 50-50 wether nor not deviation of measured norm happen when walking by distortions.
For instance a metallic pillar which runs through the building I live in deviated (50 - 410) , **-360**! But the heading around and near it where dead accurate. While some deviation of **15** effected heading with around 90 deg in another place...
I have also experienced the situation where mag measurement is near mag norm but heading gets wrong. So it can't really be used in good way I think?

And by they way, is there some way of getting value which will indicate inaccuracy in the quaternion?
