### ISSUE TITLE
Automatic / dynamic gain calculation

### ISSUE THREAD

**Issue by herbertvuijk** [xioTechnologies/Fusion#92]
In my application the amount of noise varies a lot. 98% of the time there is a lot of noise in the data (a high standard deviation on every accelero and gyro measurement)  - Period HN, 2% of the time there is much less noise (a very low standard deviation) but there is high acceleration - Period LN. 

I need the most accurate orientation determination period LN, orientation during HN I don't care about. 

The problem is that if I take a gain of 0.5 to deal with HN, the orientation determination is not so good during LN. If I take a gain of 0.1  the orientation determination works well for LN but get pretty off during the HN. 

Although I'm not interested in orientation during period HN I also need it to be fairly decent, because otherwise I start of my calculations in the LN period based on a wrong start orientation. During the HN period the device is relative in the same orientation, but exposed to a lot of noise (bouncing).

What I ended up doing was toggling the Gain programmatically between 0.5 and 0.1 based on my own HN/LN detection. This works pretty reasonable, but is not so sophisticated. I learned that in some data 0.5 /0.1 works , in other 0.4/0.2, e.t.c. Also I'm nog happy with the hard toggling, I guess I should implement some ramping up/down. 

Is there any recommendation on how to find optimal and dynamic Gain values? It would be quite awesome to do some kind of drift detection and then automatically ramp up/down gain based on that.

**Comment by xioTechnologies** [comment]
Best performance is achieved with a fixed gain and well calibrated sensors.  I expect that the improvements achieved through a dynamic gain could be shown to be a workaround for some underlying issue that should be fixed.

Please can you describe your application in a little more detail.  What sensors you are using?  What calibration has been performed?  What is the motion being measured?  It would also be useful if you could share data demonstrating the issue, either as plots or as CSV files.

**Comment by herbertvuijk** [comment]
Removed comment. Sorry for removing the details but turned out I can't disclose the details on the use case for contractual reasons. The answers are noted anyway, thanks all for the help

**Comment by LazaroFilm** [comment]
You may want to look into using two accelerometers one high G and one low g like the [X-IMU3](https://x-io.co.uk/x-imu3/) which may be a good device to use in your case, you may want to add one extra layer of waterproofing to it though.

**Comment by xioTechnologies** [comment]
Thank you for explaining.  

I understand how switching between two gains benefits your application but this behaviour and the associated heuristics are extremely application-specific.  The dynamic gain you have described would not be an appropriate feature to introduce to Fusion.  Fusion does not prevent you from implementing this behaviour yourself.

You said that you ramping the gain up/down may be preferable.  I do not see any benefit in this over hard toggling.

**Comment by xioTechnologies** [comment]
I understand how switching between two gains benefits your application but this behaviour and the associated heuristics are extremely application-specific.  The dynamic gain you have described would not be an appropriate feature to introduce to Fusion.  Fusion does not prevent you from implementing this behaviour yourself.

You said that you ramping the gain up/down may be preferable.  I do not see any benefit in this over hard toggling.

**Comment by herbertvuijk** [comment]
Thanks all.. @LazaroFilm the idea is that people use existing hardware (phones, watches) and therefor its not really possible to use an external IMO. 

@xioTechnologies Thanks you, if I discover anything interesting with regards to dynamic gain I will let you know.
