### ISSUE TITLE
accelerometer error addition during the AHRS updating step.

### ISSUE THREAD

**Issue by sinitsky96** [xioTechnologies/Fusion#95]
Hello,
After reading the thesis and going over the code of the revised AHRS, I've noticed the error of a sensor is calculated and stored in the Internal state but i could not find its usage during the updating step.
Would very much appreciate the help.
Thank you.

**Comment by xioTechnologies** [comment]
The error in inclination and heading is used to calculate the feedback on lines [143](https://github.com/xioTechnologies/Fusion/blob/main/Fusion/FusionAhrs.c#L143) and [172](https://github.com/xioTechnologies/Fusion/blob/main/Fusion/FusionAhrs.c#L172) respectively.  These feedback terms are then applied on line [188](https://github.com/xioTechnologies/Fusion/blob/main/Fusion/FusionAhrs.c#L188).

**Comment by sinitsky96** [comment]
Thank you very much.
