### ISSUE TITLE
Questions about the scope of application

### ISSUE THREAD

**Issue by WYW0** [xioTechnologies/Fusion#96]
Hello！
I collected data on a set of circular trajectories in the horizontal direction using sensors. After using these data to perform fusion algorithm calculations, strange quaternions were generated. I want to know if the fusion algorithm is not good at this method. Thank you.
![Figure_1](https://user-images.githubusercontent.com/97726874/230315003-b5d68610-0b29-4f4a-9de3-daf71bd3dba1.png)

**Comment by xioTechnologies** [comment]
You appear to have extremely high gyroscope offset errors.  I suggest that you verify that when you device is stationary, the gyroscope measures 0 degrees/s in all three axes.

**Comment by WYW0** [comment]
I re collected data with the same trajectory but more stable, and achieved acceptable results. And I noticed that x-IMU3 is about to be released. Can you tell me its overall dimensions?
![Figure_a=1_1](https://user-images.githubusercontent.com/97726874/230382977-0a445c29-f557-41e9-be7f-678f21790606.png)

**Comment by xioTechnologies** [comment]
I am pleased you've achieved acceptable performance.  Please close this issue if it is now solved.  x-IMU3 information is provided on the [x-IMU3 webpage](https://x-io.co.uk/x-imu3/).  Please contact x-io via the website for product enquires.
