### ISSUE TITLE
I have a question about your Fusion algorithm in C code

### ISSUE THREAD

**Issue by JiyoonJo** [xioTechnologies/Fusion#97]
When rotating the sensor, roll, pitch, and yaw are all normally calculated as Euler angles. However, when the sensor stops rotating, only the yaw value does not stop and continues to change to the initial state value.

Can you tell me why it's like this?

when the rotation of sensor is stopped, I want all the value(roll, pitch, yaw) to be stopped as well.

**Comment by xioTechnologies** [comment]
Please can you share a plot to better explain the issue.  For example, like the questioner in [this issue](https://github.com/xioTechnologies/Fusion/issues/96) has done.

**Comment by JiyoonJo** [comment]
I can't attach a image file of graph becasue of the security policy for my company.
Can i send a image by e-mail?
Let me know your e-mail address.

thanks for your help.

**Comment by xioTechnologies** [comment]
Please contact us using the [website](https://x-io.co.uk/contact).
